### ISSUE TITLE
Text Highlighting for Changes YAML

### ISSUE THREAD

**Issue by javajason** [f5devcentral/modern_app_jumpstart_workshop#103]
In this lab, there are several places where we are asked to change our current YAML to the YAML shown in the lab. The specific differences are summarized, but not specifically called out.
I can simply copy the YAML from the lab notes and use it to replace the entire YAML file that already exists locally on my desktop, but then I wouldn't really learn how the changes impact the application's behavior.
It would be easier (and more educational) if the entire YAML were shown (as is currently done), but the needed changes were shown in a different color.

**Comment by aknot242** [comment]
Currently, we are limited to what GitHub's Markdown engine can support. There is no format that supports both syntax and arbitrary line highlighting available at this time. There is [diff highlighting](https://stackoverflow.com/questions/62210823/how-to-format-git-insertions-deletions-in-github-markdown), however, we would lose the YAML syntax highlighting, and there would be `+` and `-` symbols at the beginning of the line that would need to be edited out by the student manually.

**Comment by codygreen** [comment]
we cannot achieve the change highlighting with the current rendering options.  We will look into this for a future lab framework.
