### ISSUE TITLE
Need to integrate API Security use case (OAuth/OIDC) into the workshop

### ISSUE THREAD

**Issue by aknot242** [f5devcentral/modern_app_jumpstart_workshop#134]
Need to:
- Add an OIDC identity provider to the deployment with some static configuration
- Extend the Brewz API to introduce protected endpoints that will consume personalization data
- Configure NGINX to integrate with it for AuthN,AuthZ (might need to use NJS to present personalization payload data to the upstream services)
- Document the scenario in the lab guide

**Comment by codygreen** [comment]
it might be helpful to break these into smaller issues using a task list

**Comment by aknot242** [comment]
@codygreen good point. This is more representative of an epic in scale than a story.
