### ISSUE TITLE
Kubeconfig generation is no longer running correctly

### ISSUE THREAD

**Issue by aknot242** [f5devcentral/modern_app_jumpstart_workshop#19]
Errors from syslog:

Jul  2 15:29:02 k3s udf-setup.sh[818]: The connection to the server 10.1.1.5:6443 was refused - did you specify the right host or port?
Jul  2 15:29:02 k3s udf-setup.sh[751]: waiting for kube api to be up...
Jul  2 15:29:12 k3s udf-setup.sh[1217]: No resources found in default namespace.
Jul  2 15:29:13 k3s udf-setup.sh[1311]: Error from server (NotFound): serviceaccounts "udf-sa" not found
Jul  2 15:40:48 k3s udf-setup.sh[8047]: fatal: not a git repository (or any of the parent directories): .git
Jul  2 15:40:48 k3s udf-setup.sh[8049]: fatal: not a git repository (or any of the parent directories): .git
Jul  2 15:40:48 k3s udf-setup.sh[8056]: Failed to print the table: Broken pipe
Jul  2 15:40:50 k3s udf-setup.sh[8074]: No resources found in default namespace.

**Comment by codygreen** [comment]
it's a race condition, the script that generates the config-udf.yaml config file executes at boot.  However, the current blueprint is an empty K8s cluster.  I'll update the blueprint to include the udf-sa at boot time.

**Comment by codygreen** [comment]
new blueprint revision resolves this issue.
