### ISSUE TITLE
Create Day-3 Lab for NGINX Plus Ingress Controller, Grafana and Prometheus

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/modern_app_jumpstart_workshop#28]
Create a Day-3 lab that extends upon the metrics demonstrated in Day-1 but with the additional metrics that NGINX Plus provides.  Utilize the NGINX Ingress Controller's Grafana dashboard.

**Comment by aknot242** [comment]
Addressed in #35 and #37 . Closing
