### ISSUE TITLE
Day-3 Progressive Deployment Lab with NGINX Plus Ingress Controller

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/modern_app_jumpstart_workshop#30]
demonstrate a canary deployment using NGINX Plus Ingress Controller.  Show how we can go farther than we did on Day 1 due to our limitations of NIC OSS.

**Comment by aknot242** [comment]
@codygreen do you think we need to highlight some of these extra capabilities in the lab guide editorial, or is this something we should handle in the presentations? If the latter, I will close this as I think we accomplished this with the day 3 scenarios.

**Comment by codygreen** [comment]
I think A/B and canary are good for the lab.  The others can be discussed in the presentation.
