### ISSUE TITLE
Markdown Render Error for Install NIC

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/modern_app_jumpstart_workshop#38]
When setting the TAG variable, markdown is not presenting the full command: 
https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/install_nic.md?plain=1#L43

**Comment by codygreen** [comment]
Same issue for the variable replacement:

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/install_nic.md?plain=1#L52

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/install_nic.md?plain=1#L86

**Comment by codygreen** [comment]
Same issue for the prometheus and grafana install steps:

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/install_grafana.md?plain=1#L14

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/install_grafana.md?plain=1#L14

**Comment by aknot242** [comment]
@codygreen are you seeing these render errors in VSCode, or in GitHub?

**Comment by codygreen** [comment]
Same issue for brews:

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/32d08a4ea51b1a4c47f22f75e59a3b72b121e290/docs/ingress/brewz.md?plain=1#L14

**Comment by codygreen** [comment]
The render issue is with GitHub Pages, it renders fine when viewing it in VSCode and when you view the code on GitHub.com.

**Comment by codygreen** [comment]
This seems to be a GitHub pages issue as Jekyll uses Liquid and the {{ }} characters are reserved for Liquid use. 

https://github.com/just-the-docs/just-the-docs/issues/414

**Comment by codygreen** [comment]
still an issue for:
https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/fc59b88d4c552d106d8dfc69ae2cfdf95c661f5c/docs/ingress/install_nic.md?plain=1#L88

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/fc59b88d4c552d106d8dfc69ae2cfdf95c661f5c/docs/ingress/install_grafana.md?plain=1#L14

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/fc59b88d4c552d106d8dfc69ae2cfdf95c661f5c/docs/ingress/build_nic.md?plain=1#L61

**Comment by aknot242** [comment]
Should we just ask lab participants to view the guide from their forked repo in GitHub?
