### ISSUE TITLE
virtual-server.yaml in docs missing recommendations and inventory

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/modern_app_jumpstart_workshop#67]
In the [rate limit scenarion](https://f5devcentral.github.io/modern_app_jumpstart_workshop/scenario/rate-limit.html), the yaml shown for how the virtual-server.yaml should look is missing /inventory and /recommendations routes. This may be that the content is prematurely showing the decoupling from the next exercise.

**Comment by aknot242** [comment]
This is actually a source file issue. WIll address.
