### ISSUE TITLE
after Grafana dashboard there are no next steps

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/modern_app_jumpstart_workshop#70]
Should the document provide a link back to the scenarios list?

**Comment by aknot242** [comment]
@mjmenger in which document is this?

**Comment by mjmenger** [comment]
Sorry. At the bottom of https://f5devcentral.github.io/modern_app_jumpstart_workshop/scenario/grafana-dashboard.html

there is no Next Step section. Should this point back to the Scenarios list at https://f5devcentral.github.io/modern_app_jumpstart_workshop/
