### ISSUE TITLE
NGINX Dashboard access method is missing from UDF access menu

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/modern_app_jumpstart_workshop#73]
At the end of [NGINX Dashboard](https://f5devcentral.github.io/modern_app_jumpstart_workshop/ingress/install_nic.html#nginx-dashboard), the Dashboard access method referenced is missing from the access menu in UDF.

**Comment by aknot242** [comment]
@codygreen should probably discuss how we want to handle this

**Comment by codygreen** [comment]
Need to also instruct the user to add `/dashboard.html` to the URI

**Comment by aknot242** [comment]
FYI, fixed @jmcalalang
