### ISSUE TITLE
documentation suggestions: don't accidentally commit your kubeconfig file

### ISSUE THREAD

**Issue by mikeoleary** [f5devcentral/modern_app_jumpstart_workshop#80]
[Instructions](https://f5devcentral.github.io/modern_app_jumpstart_workshop/scenario/setup.html#generate-local-kubeconfig) for generating the local kubeconfig don't specify where you should save your kubeconfig file.

It's likely someone will accidentally commit their kubeconfig file if they put it in the directory of the repo and then commit all changes.

- can we remind people to NOT commit their kubeconfig file? Probably best to put that note along where the [instructions ](https://f5devcentral.github.io/modern_app_jumpstart_workshop/scenario/rate-limit.html)tell you to commit your changes. 
- also, could we get an example of exporting the KUBECONFIG env var? Might help folks based on class questions today.

thanks!!

**Comment by codygreen** [comment]
we should also add config-udf.yaml to the .gitignore file
