### ISSUE TITLE
Rate-limit lab next steps has wrong link

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/modern_app_jumpstart_workshop#81]
Rate-limit lab links to the Grafana lab but it needs to link to the A/B test lab.

https://github.com/f5devcentral/modern_app_jumpstart_workshop/blob/dface53665051981eda6c6719231a87fa473d55e/docs/scenario/rate-limit.md?plain=1#L79

**Comment by aknot242** [comment]
fixed in PR #82
